version: '3'
services:
  mimic3:
    image: 'mycroftai/mimic3'
    ports:
      - '59125:59125'
    volumes:
      - type: bind
        source: ~/.local/share/mycroft/mimic3
        target: /home/mimic3/.local/share/mycroft/mimic3
    restart: always
  node-app:
    build:
      context: .
      args:
        - 'BASEURL=http://localhost:8889'
        - PICOVOICE_ACCESS_KEY # todo, done to this
    ports:
      - '${PORT}:8889'
    volumes:
      - type: bind
        source: ~/Library/Mobile Documents/com~apple~CloudDocs/botplot
        target: /usr/src/data
    restart: always
    environment:
      - PORT
      - 'SQLITE_DB=/usr/src/data/sqlite.db'
      - OPENAI_API_KEY
      - OPENAI_API_ORG
      - PINECONE_API_KEY
      - PINECONE_ENVIRONMENT
      - PICOVOICE_ACCESS_KEY
      - PINECONE_INDEX
      - SERPAPI_API_KEY
      - GOOGLE_API_KEY
    depends_on:
      - mimic3
