#!/usr/bin/env bash

set -x

if [ -z "$SQLITE_DB" ]; then
    echo "SQLITE_DB must be set"
    exit 1
fi

if [ -f "${SQLITE_DB}" ]; then
    mv "${SQLITE_DB}" "${SQLITE_DB}.$(date +%s).bak" || (echo "Failed to backup ${SQLITE_DB}" && exit 1)
    rm "${SQLITE_DB}" &2>/dev/null
    rm "${SQLITE_DB}-wal" &2>/dev/null
    rm "${SQLITE_DB}-shm" &2>/dev/null
fi

cat ./scripts/sql/init.sql | sqlite3 "${SQLITE_DB}"

set +x
